name: CD on tag

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build_test_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Make main.sh executable
        run: chmod +x main.sh

      - name: Setup environment
        run: ./main.sh setup

      - name: Run unit tests
        run: ./main.sh test

      - name: Build the package
        run: ./main.sh build
      
      - name: Upload the package
        run: ./main.sh upload
        # env:
        #   TWINE_USERNAME: __token__
        #   TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

